export const GET_INPUT_VALUE = "GET_INPUT_VALUE";
export const GET_DOC_EMPL = "GET_DOC_EMPL";
export const RESET_VALUE = "RESET_VALUE";

export const GET_DOC_SELECT = "GET_DOC_SELECT"
export const SAVE_IDS = "SAVE_IDS"
export const CLEAN_IDS_DOC = "CLEAN_IDS_DOC"
export const DOCU_DEL_EMPLEADO = "DOCU_DEL_EMPLEADO"
export const DELETE_DOC_EMPLEADO = "DELETE_DOC_EMPLEADO"