export const ADD_DOMICILIOS = "ADD_DOMICILIOS";
export const ADD_ONEDOMICILIO = "ADD_ONEDOMICILIO";
export const SELECT_PROVINCIA = "SELECT_PROVINCIA";
export const SELECT_DEPARTAMENTO = "SELECT_DEPARTAMENTO";
export const SELECT_BARRIO = "SELECT_BARRIO";
export const SELECT_ID_DOMICILIO = "SELECT_ID_DOMICILIO";
export const ADD_NEW_DOMICILIO = "ADD_NEW_DOMICILIO";
export const DELETE_ONE_DOMICILIO = "DELETE_ONE_DOMICILIO";
export const SET_PREDETERMINADO = "SET_PREDETERMINADO";
export const ADD_DOM_TABLE = "ADD_DOM_TABLE"
export const SAVE_IDS_DOM = "SAVE_IDS_DOM"

export const RECHARGE = "RECHARGE"
export const CLEAR_ID_DOM = "CLEAR_ID_DOM"