export const ADD_EMPLOYE = "ADD_EMPLOYE";
export const REMOVE_EMPLOYE = "REMOVE_EMPLOYE";
export const SELECTED_EMPLOYE = "SELECTED_EMPLOYE";
export const UPDATE_EMPLOYE = "UPDATE_EMPLOYE";
export const ADD_ONE_EMPLOYE = "ADD_ONE_EMPLOYE";