export const ADD_EMPLOYE = "ADD_EMPLOYE";

export const REMOVE_EMPLOYE = "REMOVE_EMPLOYE";

export const SELECTED_EMPLOYE = "SELECTED_EMPLOYE";

export const UPDATE_EMPLOYE = "UPDATE_EMPLOYE";

export const ADD_ONE_EMPLOYE = "ADD_ONE_EMPLOYE";

export const GET_INPUT_VALU_BROWSER = "GET_INPUT_VALU_BROWSER";

export const GET_EMPLOYES = "GET_EMPLOYES";

export const DISABLE_FUNCTIONS = "DISABLE_FUNCTIONS";

export const CLEAN_EMPLOYE = "CLEAN_EMPLOYE"