export const GET_INPUT_VALUES_EXTRAS = "GET_INPUT_VALUES_EXTRAS";


export const GET_DE_SELECTED = "GET_DE_SELECTED"
export const SAVE_ID_DE = "SAVE_ID_DE"
export const CLEAN_ID_DE = "CLEAN_ID_DE"
export const ADD_DATOSE_EMP = "ADD_DATOSE_EMP"
export const DELETE_DE_EMP = "DELETE_DE_EMP"

