export const ADD_FAMILIA = "ADD_FAMILIA";
export const ADD_FAMILIAR_ID = "ADD_FAMILIAR_ID";
export const ADD_FAMILIAR = "ADD_FAMILIAR";

export const DATOS_FAMILIAR_X_EMPLEADO = "DATOS_FAMILIAR_X_EMPLEADO"