export const SET_LOADING = "SET_LOADING";
export const AXIOS_SUCCESS = "AXIOS_SUCCESS";
export const AXIOS_ERROR = "AXIOS_ERROR";

export const ADD_ESTADOS = "ADD_ESTADOS";
export const ADD_ESTADOSCIVILES = "ADD_ESTADOSCIVILES";
export const ADD_PAISES = "ADD_PAISES";
export const ADD_ESTUDIOS = "ADD_ESTUDIOS";
export const ADD_TIPOSDOCUMENTO = "ADD_TIPOSDOCUMENTO";
export const ADD_CARGOS = "ADD_CARGOS";
export const ADD_TAREASDESEMPEÑADAS = "ADD_TAREASDESEMPEÑADAS";
export const ADD_PARENTESCOS = "ADD_PARENTESCOS";
export const ADD_FORMASPAGO = "ADD_FORMASPAGO";
export const ADD_MODOSCONTRATACION = "ADD_MODOSCONTRATACION";
export const ADD_MODOSLIQUIDACION = "ADD_MODOSLIQUIDACION";
export const ADD_EMPLEADORES = "ADD_EMPLEADORES";

export const ADD_DOMICLIOS = "ADD_DOMICLIOS";
export const ADD_CALLES = "ADD_CALLES";
export const ADD_DEPARTAMENTOS = "ADD_DEPARTAMENTOS";
export const ADD_LOCALIDADES = "ADD_LOCALIDADES";
export const ADD_PROVINCIAS = "ADD_PROVINCIAS";
export const ADD_BARRIOS = "ADD_BARRIOS";