export const SET_LOADING = "SET_LOADING";
export const AXIOS_SUCCESS = "AXIOS_SUCCESS";
export const AXIOS_ERROR = "AXIOS_ERROR";

export const ADD_ESTADOS = "ADD_ESTADOS";
export const ADD_ESTADOSCIVILES = "ADD_ESTADOSCIVILES";
export const ADD_PAISES = "ADD_PAISES";
export const ADD_ESTUDIOS = "ADD_ESTUDIOS";
export const ADD_TIPOSDOCUMENTO = "ADD_TIPOSDOCUMENTO";
export const ADD_CARGOS = "ADD_CARGOS";
export const ADD_TAREASDESEMPEÑADAS = "ADD_TAREASDESEMPEÑADAS";
export const ADD_PARENTESCOS = "ADD_PARENTESCOS";
export const ADD_FORMASPAGO = "ADD_FORMASPAGO";
export const ADD_MODOSCONTRATACION = "ADD_MODOSCONTRATACION";
export const ADD_MODOSLIQUIDACION = "ADD_MODOSLIQUIDACION";
export const ADD_EMPLEADORES = "ADD_EMPLEADORES";

export const ADD_DOMICLIOS = "ADD_DOMICLIOS";
export const ADD_CALLES = "ADD_CALLES";
export const ADD_DEPARTAMENTOS = "ADD_DEPARTAMENTOS";
export const ADD_LOCALIDADES = "ADD_LOCALIDADES";
export const ADD_PROVINCIAS = "ADD_PROVINCIAS";
export const ADD_BARRIOS = "ADD_BARRIOS";

export const ADD_FAMILIARES = "ADD_FAMILIARES";
export const ADD_NEW_FAMILIAR = "ADD_NEW_FAMILIAR";
export const DELETE_ONE_FAMILIAR = "DELETE_ONE_FAMILIAR";


export const ADD_CONVENIOS = "ADD_CONVENIOS";
export const ADD_CATEGORIAS = "ADD_CATEGORIAS";
export const ADD_AGRUPAMIENTOS = "ADD_AGRUPAMIENTOS";
export const ADD_CENTRO_COSTO = "ADD_CENTRO_COSTO";
export const ADD_SECTOR_DEPTO = "ADD_SECTOR_DEPTO";
export const ADD_OBRAS_SOCIALES = "ADD_OBRAS_SOCIALES";
export const ADD_LUGARES_DE_PAGO = "ADD_LUGARES_DE_PAGO";
export const ADD_BANCOS = "ADD_BANCOS";
export const ADD_DIRECCIONES = "ADD_DIRECCIONES";
export const ADD_SINDICATOS = "ADD_SINDICATOS";
export const ADD_ESQUEMAS = "ADD_ESQUEMAS";


export const ADD_NEW_ESCI = "ADD_NEW_ESCI";
export const ADD_NEW_ESTUDIO = "ADD_NEW_ESTUDIO";

