export const SELECTED_OPTION = "SELECTED_OPTION";
export const OPTIONS_FORMULARIO = "OPTIONS_FORMULARIO";

export const ADD_ONE_LICENCIA = "ADD_ONE_LICENCIA";
export const ADD_DETALLE_LICENCIA  ="ADD_DETALLE_LICENCIA";
export const ADD_SELECT_DETALLE = "ADD_SELECT_DETALLE";

export const UPDATE_DETALLE = "UPDATE_DETALLE";

export const ADD_NEW_DETALLE = "ADD_NEW_DETALLE";
export const DELETE_DET_LIC = "DELETE_DET_LIC";

export const CLEAR_LIC_SELECT = "CLEAR_LIC_SELECT"

export const SAVE_IDS_LIC = "SAVE_IDS_LIC"
export const CLEAR_IDS_LIC = "CLEAR_IDS_LIC"
export const ID_SELECT = "ID_SELECT"

export const ADD_LIC_EMPLEADOS = "ADD_LIC_EMPLEADOS"
export const DELETE_LIC_EMPLEADO = "DELETE_LIC_EMPLEADO"
export const LICENCIA_SELECT = "LICENCIA_SELECT"