export const SELECTED_OPTION = "SELECTED_OPTION";
export const OPTIONS_FORMULARIO = "OPTIONS_FORMULARIO";

export const ADD_ONE_LICENCIA = "ADD_ONE_LICENCIA";
export const ADD_DETALLE_LICENCIA  ="ADD_DETALLE_LICENCIA";
export const ADD_SELECT_DETALLE = "ADD_SELECT_DETALLE";

export const UPDATE_DETALLE = "UPDATE_DETALLE";

export const ADD_NEW_DETALLE = "ADD_NEW_DETALLE";
export const DELETE_DET_LIC = "DELETE_DET_LIC";

export const CLEAR_LIC_SELECT = "CLEAR_LIC_SELECT"

export const DELETE_ONE_LICENCIA = "DELETE_ONE_LICENCIA";

export const DELETE_LIST_ITEM = "DELETE_LIST_ITEM"
export const RELOAD_ITEM = "RELOAD_ITEM"
export const SAVE_ID_LIC = "SAVE_ID_LIC"
export const CLEAN_IDS = "CLEAN_IDS"

export const GET_ID = "GET_ID"