export const ADD_SELECTED_EC = "ADD_SELECTED_EC";
export const GET_ESTADOSCIVILES = "GET_ESTADOSCIVILES";

export const ADD_SELECTED_ESTUDIO = "ADD_SELECTED_ESTUDIO"
export const GET_ESTUDIOS = "GET_ESTUDIOS"

export const ADD_SELECTED_TIPODOC = "ADD_SELECTED_TIPO_DOC"
export const GET_TIPOSDOC = "GET_TIPOS_DOC"

export const ADD_SELECTED_PARENTESCO = "ADD_SELECTED_PARENTESCO"
export const GET_PARENTESCOS = "GET_PARENTESCOS"

export const ADD_SELECTED_ESTADO = "ADD_SELECTED_ESTADO"
export const GET_ESTADOS = "GET_ESTADOS"

export const ADD_SELECTED_FORMAPAGO = "ADD_SELECTED_FORMAPAGO"
export const GET_FORMASPAGO = "GET_FORMAPAGO"

export const ADD_SELECTED_CARGO = "ADD_SELECTED_CARGO"
export const GET_CARGOS = "GET_CARGOS"

export const ADD_SELECTED_TAREA = "ADD_SELECTED_TAREA"
export const GET_TAREAS = "GET_TAREAS"

export const ADD_SELECTED_MODOCONT = "ADD_SELECTED_MODOCONT"
export const GET_MODOSCONT = "GET_MODOSCONT"

export const ADD_SELECTED_MODOLIQ = "ADD_SELECTED_MODOLIQ"
export const GET_MODOSLIQ = "GET_MODOSLIQ"

export const ADD_SELECTED_PROVINCIA = "ADD_SELECTED_PROVINCIA"
export const GET_PROVINCIAS = "GET_PROVINCIAS"

export const ADD_SELECTED_DEPTO = "ADD_SELECTED_DEPTO"
export const GET_DEPTOS = "GET_DEPTOS"

export const ADD_SELECTED_LOCALIDAD = "ADD_SELECTED_LOCALIDAD"
export const GET_LOCALIDADES = "GET_LOCALIDADES"

export const ADD_SELECTED_BARRIO = "ADD_SELECTED_BARRIO"
export const GET_BARRIOS = "GET_BARRIOS"






// PARA LIQUIDACION (NO VAN)
export const ADD_SELECTED_BANCO = "ADD_SELECTED_BANCO"
export const GET_BANCOS = "GET_BANCOS"

export const ADD_SELECTED_SINDICATO = "ADD_SELECTED_SINDICATO"
export const GET_SINDICATOS = "GET_SINDICATOS"

export const ADD_SELECTED_CENTROCOSTO = "ADD_SELECTED_CENTROCOSTO"
export const GET_CENTROSCOSTO = "GET_CENTROSCOSTO"






export const CANCEL_MODALS = "CANCEL_MODALS";


