export const ADD_SELECTED_EC = "ADD_SELECTED_EC";
export const GET_ESTADOSCIVILES = "GET_ESTADOSCIVILES";

export const ADD_SELECTED_ESTUDIO = "ADD_SELECTED_ESTUDIO"
export const GET_ESTUDIOS = "GET_ESTUDIOS"


// TYPE PARA POSTEAR
export const ADD_PETITION_VALUE = "ADD_PETITION_VALUE";


export const CANCEL_MODALS = "CANCEL_MODALS";