export const ADD_SELECTED_EC = "ADD_SELECTED_EC";
export const GET_ESTADOSCIVILES = "GET_ESTADOSCIVILES";

export const ADD_SELECTED_ESTUDIO = "ADD_SELECTED_ESTUDIO"
export const GET_ESTUDIOS = "GET_ESTUDIOS"

export const ADD_SELECTED_TIPODOC = "ADD_SELECTED_TIPO_DOC"
export const GET_TIPOSDOC = "GET_TIPOS_DOC"

export const ADD_SELECTED_PARENTESCO = "ADD_SELECTED_PARENTESCO"
export const GET_PARENTESCOS = "GET_PARENTESCOS"

export const ADD_SELECTED_ESTADO = "ADD_SELECTED_ESTADO"
export const GET_ESTADOS = "GET_ESTADOS"

export const ADD_SELECTED_FORMAPAGO = "ADD_SELECTED_FORMAPAGO"
export const GET_FORMASPAGO = "GET_FORMAPAGO"

export const ADD_SELECTED_CARGO = "ADD_SELECTED_CARGO"
export const GET_CARGOS = "GET_CARGOS"

export const ADD_SELECTED_TAREA = "ADD_SELECTED_TAREA"
export const GET_TAREAS = "GET_TAREAS"




export const CANCEL_MODALS = "CANCEL_MODALS";

export const SET_REFETCH = "SET_REFETCH"


