export const GET_TANTERIORES = "GET_TANTERIORES";

export const GET_INPUT = "GET_INPUT";
export const ADD_TRABAJO_ANTERIOR = "ADD_TRABAJO_ANTERIOR";
export const GET_ID_TRABAJO = "GET_ID_TRABAJO";
export const DELETE_ONE_TRABAJO = "DELETE_ONE_TRABAJO";
export const GET_TRABAJO = "GET_TRABAJO";

export const DELETE_LIST_ITEM = "DELETE_LIST_ITEM"
export const RELOAD_ITEM = "RELOAD_ITEM"
export const SAVE_ID = "SAVE_ID"
export const CLEAN_IDS = "CLEAN_IDS"