export const GET_TANTERIORES = "GET_TANTERIORES";

export const GET_INPUT = "GET_INPUT";
export const ADD_TRABAJO_ANTERIOR = "ADD_TRABAJO_ANTERIOR";
export const GET_ID_TRABAJO = "GET_ID_TRABAJO";
export const DELETE_ONE_TRABAJO = "DELETE_ONE_TRABAJO";